### ISSUE TITLE
Widget Relógio com clima

### ISSUE THREAD

**Issue by Josodl** [miuibrasil/MIUIBrasil-8-XML-for-Xiaomi.eu#2]
Olá. Parabéns pelo excelente trabalho de tradução. 
Percebi um pequeno bug no Widget Relógio, o que tem o clima mais completo...
A palavra "Humidade" está em polonês... Aparece como Wilgotność... 
Único bug que percebi até o momento em todo o SO.
Parabéns e contem comigo. Vim migrado do Cyanogemod.
Forte abraço e à disposição!!!

**Comment by Josodl** [comment]
Perdão pelo esquecimento...
Redmi PRO_Omega       xiaomi.eu_multi_HMPro_6.9.15_v8-6.0 
O erro percebi já na versão 6.9.8
Parabéns novamente e obrigado por colocarem-se à disposição da comunidade.

**Comment by ingbrzy** [comment]
not translation issue, its hardcoded into the widget...
