### ISSUE TITLE
Partes do Sistema em inglês

### ISSUE THREAD

**Issue by MarcosF97** [miuibrasil/MIUIBrasil-8-XML-for-Xiaomi.eu#4]
Existem várias partes do sistema em inglês no XML que a Xiaomi.eu utiliza, como por exemplo a personalização da tela de início, as opções são "Themes, Widgets, Wallpappers, Effects". Nas configurações do Modo de Criança tá tudo em inglês também (inclusive o próprio menu tá Child Mode). Por fim, nas configurações de senha de bloqueio de privacidade, no campo "A senha de bloqueio de privacidade bloqueia", onde você pode escolher mensagens, contatos, etc, está tudo em inglês, também! Consertem que só falta isso pra ser perfeito!

**Comment by mattbittencourt** [comment]
@MarcosF97 Obrigado pelo feedback. Geralmente a tradução presente nas ROMs Xiaomi.eu tem atraso de 1 semana entre as nossas traduções, pois eles compilam a ROM no dia em que recebemos a tradução para trabalhar. Desta forma, embora sempre esteja atualizada, em algumas versões itens podem aparecer em inglês como você disse :)
